# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4373ba26ef15f900fbb98fc7ad292bad793014c560fbf217330fffd27b1800190d0d68b192fa96d1834811645773524f8fc0ffc41577a47218edbd0f4f31bf79

test:
  secret_key_base: 6cb9545f2cb09db5c77dec764a4aec3acf53d4db846126ee732523ee102135fc6c826c3ec6c177125d23ead201eeb05f78a10668bbdcf5e4752a3b1badadfb2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
